apiVersion: v1
kind: Service
metadata:
  name: demo-chat-lb
spec:
  type: LoadBalancer
  ports:
    - port: 8000
      targetPort: 9000
      name: healthz
    - port: 8080
      targetPort: 8080
      name: ws-server

  selector:
    app: demo-chat